// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/events/inventory.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_events_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_events_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedEvent) Reset() {
	*x = OrderCreatedEvent{}
	mi := &file_proto_events_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedEvent) ProtoMessage() {}

func (x *OrderCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedEvent.ProtoReflect.Descriptor instead.
func (*OrderCreatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreatedEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCreatedEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCreatedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderCreatedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderCreatedEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type InventoryReservedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ReservedItems []*OrderItem           `protobuf:"bytes,5,rep,name=reserved_items,json=reservedItems,proto3" json:"reserved_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReservedEvent) Reset() {
	*x = InventoryReservedEvent{}
	mi := &file_proto_events_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReservedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReservedEvent) ProtoMessage() {}

func (x *InventoryReservedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReservedEvent.ProtoReflect.Descriptor instead.
func (*InventoryReservedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryReservedEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *InventoryReservedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InventoryReservedEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InventoryReservedEvent) GetReservedItems() []*OrderItem {
	if x != nil {
		return x.ReservedItems
	}
	return nil
}

var File_proto_events_inventory_proto protoreflect.FileDescriptor

const file_proto_events_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/events/inventory.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xcb\x01\n" +
	"\x11OrderCreatedEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12'\n" +
	"\x05items\x18\x06 \x03(\v2\x11.events.OrderItemR\x05items\"\xa1\x01\n" +
	"\x16InventoryReservedEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\x0ereserved_items\x18\x05 \x03(\v2\x11.events.OrderItemR\rreservedItemsB\x1bZ\x19inventory/internal/eventsb\x06proto3"

var (
	file_proto_events_inventory_proto_rawDescOnce sync.Once
	file_proto_events_inventory_proto_rawDescData []byte
)

func file_proto_events_inventory_proto_rawDescGZIP() []byte {
	file_proto_events_inventory_proto_rawDescOnce.Do(func() {
		file_proto_events_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_inventory_proto_rawDesc), len(file_proto_events_inventory_proto_rawDesc)))
	})
	return file_proto_events_inventory_proto_rawDescData
}

var file_proto_events_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_events_inventory_proto_goTypes = []any{
	(*OrderItem)(nil),              // 0: events.OrderItem
	(*OrderCreatedEvent)(nil),      // 1: events.OrderCreatedEvent
	(*InventoryReservedEvent)(nil), // 2: events.InventoryReservedEvent
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_proto_events_inventory_proto_depIdxs = []int32{
	3, // 0: events.OrderCreatedEvent.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: events.OrderCreatedEvent.items:type_name -> events.OrderItem
	0, // 2: events.InventoryReservedEvent.reserved_items:type_name -> events.OrderItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_events_inventory_proto_init() }
func file_proto_events_inventory_proto_init() {
	if File_proto_events_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_inventory_proto_rawDesc), len(file_proto_events_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_inventory_proto_goTypes,
		DependencyIndexes: file_proto_events_inventory_proto_depIdxs,
		MessageInfos:      file_proto_events_inventory_proto_msgTypes,
	}.Build()
	File_proto_events_inventory_proto = out.File
	file_proto_events_inventory_proto_goTypes = nil
	file_proto_events_inventory_proto_depIdxs = nil
}
