// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/events/kitchen.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_events_kitchen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_kitchen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_events_kitchen_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReadyForKitchenEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyForKitchenEvent) Reset() {
	*x = ReadyForKitchenEvent{}
	mi := &file_proto_events_kitchen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyForKitchenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyForKitchenEvent) ProtoMessage() {}

func (x *ReadyForKitchenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_kitchen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyForKitchenEvent.ProtoReflect.Descriptor instead.
func (*ReadyForKitchenEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_kitchen_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyForKitchenEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReadyForKitchenEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type KitchenAcceptedOrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KitchenAcceptedOrderEvent) Reset() {
	*x = KitchenAcceptedOrderEvent{}
	mi := &file_proto_events_kitchen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KitchenAcceptedOrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenAcceptedOrderEvent) ProtoMessage() {}

func (x *KitchenAcceptedOrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_kitchen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenAcceptedOrderEvent.ProtoReflect.Descriptor instead.
func (*KitchenAcceptedOrderEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_kitchen_proto_rawDescGZIP(), []int{2}
}

func (x *KitchenAcceptedOrderEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderCookedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCookedEvent) Reset() {
	*x = OrderCookedEvent{}
	mi := &file_proto_events_kitchen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCookedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCookedEvent) ProtoMessage() {}

func (x *OrderCookedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_kitchen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCookedEvent.ProtoReflect.Descriptor instead.
func (*OrderCookedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_kitchen_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCookedEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCookedEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_events_kitchen_proto protoreflect.FileDescriptor

const file_proto_events_kitchen_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/events/kitchen.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"Z\n" +
	"\x14ReadyForKitchenEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.events.OrderItemR\x05items\"6\n" +
	"\x19KitchenAcceptedOrderEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\"V\n" +
	"\x10OrderCookedEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.events.OrderItemR\x05itemsB\x19Z\x17kitchen/internal/eventsb\x06proto3"

var (
	file_proto_events_kitchen_proto_rawDescOnce sync.Once
	file_proto_events_kitchen_proto_rawDescData []byte
)

func file_proto_events_kitchen_proto_rawDescGZIP() []byte {
	file_proto_events_kitchen_proto_rawDescOnce.Do(func() {
		file_proto_events_kitchen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_kitchen_proto_rawDesc), len(file_proto_events_kitchen_proto_rawDesc)))
	})
	return file_proto_events_kitchen_proto_rawDescData
}

var file_proto_events_kitchen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_events_kitchen_proto_goTypes = []any{
	(*OrderItem)(nil),                 // 0: events.OrderItem
	(*ReadyForKitchenEvent)(nil),      // 1: events.ReadyForKitchenEvent
	(*KitchenAcceptedOrderEvent)(nil), // 2: events.KitchenAcceptedOrderEvent
	(*OrderCookedEvent)(nil),          // 3: events.OrderCookedEvent
}
var file_proto_events_kitchen_proto_depIdxs = []int32{
	0, // 0: events.ReadyForKitchenEvent.items:type_name -> events.OrderItem
	0, // 1: events.OrderCookedEvent.items:type_name -> events.OrderItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_events_kitchen_proto_init() }
func file_proto_events_kitchen_proto_init() {
	if File_proto_events_kitchen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_kitchen_proto_rawDesc), len(file_proto_events_kitchen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_kitchen_proto_goTypes,
		DependencyIndexes: file_proto_events_kitchen_proto_depIdxs,
		MessageInfos:      file_proto_events_kitchen_proto_msgTypes,
	}.Build()
	File_proto_events_kitchen_proto = out.File
	file_proto_events_kitchen_proto_goTypes = nil
	file_proto_events_kitchen_proto_depIdxs = nil
}
