// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/events/delivery.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_events_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_events_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderReadyForDeliveryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,4,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerId      string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderReadyForDeliveryEvent) Reset() {
	*x = OrderReadyForDeliveryEvent{}
	mi := &file_proto_events_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReadyForDeliveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReadyForDeliveryEvent) ProtoMessage() {}

func (x *OrderReadyForDeliveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReadyForDeliveryEvent.ProtoReflect.Descriptor instead.
func (*OrderReadyForDeliveryEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *OrderReadyForDeliveryEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderReadyForDeliveryEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderReadyForDeliveryEvent) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *OrderReadyForDeliveryEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type DeliveryStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStartedEvent) Reset() {
	*x = DeliveryStartedEvent{}
	mi := &file_proto_events_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStartedEvent) ProtoMessage() {}

func (x *DeliveryStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStartedEvent.ProtoReflect.Descriptor instead.
func (*DeliveryStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryStartedEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type DeliveryCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryCompletedEvent) Reset() {
	*x = DeliveryCompletedEvent{}
	mi := &file_proto_events_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryCompletedEvent) ProtoMessage() {}

func (x *DeliveryCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryCompletedEvent.ProtoReflect.Descriptor instead.
func (*DeliveryCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryCompletedEvent) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_proto_events_delivery_proto protoreflect.FileDescriptor

const file_proto_events_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/events/delivery.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xac\x01\n" +
	"\x1aOrderReadyForDeliveryEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.events.OrderItemR\x05items\x12)\n" +
	"\x10delivery_address\x18\x04 \x01(\tR\x0fdeliveryAddress\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\"1\n" +
	"\x14DeliveryStartedEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\"3\n" +
	"\x16DeliveryCompletedEvent\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderIdB\x1aZ\x18delivery/internal/eventsb\x06proto3"

var (
	file_proto_events_delivery_proto_rawDescOnce sync.Once
	file_proto_events_delivery_proto_rawDescData []byte
)

func file_proto_events_delivery_proto_rawDescGZIP() []byte {
	file_proto_events_delivery_proto_rawDescOnce.Do(func() {
		file_proto_events_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_delivery_proto_rawDesc), len(file_proto_events_delivery_proto_rawDesc)))
	})
	return file_proto_events_delivery_proto_rawDescData
}

var file_proto_events_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_events_delivery_proto_goTypes = []any{
	(*OrderItem)(nil),                  // 0: events.OrderItem
	(*OrderReadyForDeliveryEvent)(nil), // 1: events.OrderReadyForDeliveryEvent
	(*DeliveryStartedEvent)(nil),       // 2: events.DeliveryStartedEvent
	(*DeliveryCompletedEvent)(nil),     // 3: events.DeliveryCompletedEvent
}
var file_proto_events_delivery_proto_depIdxs = []int32{
	0, // 0: events.OrderReadyForDeliveryEvent.items:type_name -> events.OrderItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_events_delivery_proto_init() }
func file_proto_events_delivery_proto_init() {
	if File_proto_events_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_delivery_proto_rawDesc), len(file_proto_events_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_delivery_proto_goTypes,
		DependencyIndexes: file_proto_events_delivery_proto_depIdxs,
		MessageInfos:      file_proto_events_delivery_proto_msgTypes,
	}.Build()
	File_proto_events_delivery_proto = out.File
	file_proto_events_delivery_proto_goTypes = nil
	file_proto_events_delivery_proto_depIdxs = nil
}
